SilviaPabon/AUTO-UPB

- src/public/styles/base/_globals.scss
- src/public/styles/components/_components.scss
- src/public/styles/main.scss
Cambios en:
- _globas.scss: Variables de color, fuente y tamaño de fuente.
- _components.scss: Primera implementación de botones base y contenedor de cards responsive.
- main.scss: Importe del archivo _components.scss.
Se agregaron las variables de color, tamaño de fuente y tipo de fuente en SASS, así como los estilos base para los botones y contenedores de tarjetas. 
No aplica. 
[VÍDEO MOSTRANDO LA CARACTERÍSTICA EN LOOM](https://www.loom.com/share/641b8fecf0d94dbda86ec7c9d7347515)
No aplica.
> Variables y componentes iniciales de SASS.

- src/database/creation_script.sql
Creación del archivo .sql para el script de creación de la base de datos (vacío).
No aplica. 
No aplica. 
No aplica.  
No aplica.
> Create Empty SQL file.

- src/database/SQL/query_db_pi.sql
- src/database/SQL/query_inserts.sql
- src/database/SQL/query_procedures.sql
- src/database/SQL/query_triggers.sql
- src/database/creation_script.sql
Cambios en:
- creation_script.sql: Se eliminó archivo innecesario.
- query_db_pi.sql: Script de creación de tablas.
- query_inserts.sql: Script de inserts.
- query_procedures.sql: Script de procedimientos almacenados.
- query_triggers.sql: Disparadores.
Se agregaron los SCRIPTS iniciales para poder trabajar con la base de datos. Se contiene una versión inicial del manejo de logs.
No aplica. 
[VÍDEO RESÚMEN EN LOOM ](https://www.loom.com/share/d6f61e2c17324e86b4ad9cc342ea55f6)
No aplica.
> SCRIPTS INICIALES PARA LA BASE DE DATOS

- docs/Enlaces a documentos y manuales internos.txt
Fue creado el manual de politicas de recuperacion y respaldo de informacion para la empresa WearCar
Se creó el documento .txt para la publicacion de los enlaces de los manuales
No aplica
No aplica
> Manual de Respaldo

- src/controllers/admin_controller.js
- src/database/SQL/query_procedures.sql
- src/index.js
- src/libs/passport.js
- src/public/scripts/signup_admin_validate.js
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/routes/admin.js
- src/routes/router.js
- src/views/auth/create_acc_admin.ejs
Se realizó el backend para la interfaz de creación de cuentas por parte de Admin. Se tomó por base para la interfaz, el formulario de registro previamente creado.
https://www.loom.com/share/8c46faadadbc4b73849f0ee826eea26f
Ver los comentarios en los commits.
> Interfaces y validación de creación de cuentas por Admin

- docs/Enlaces a documentos y manuales internos.txt
- src/views/auth/create_acc_admin.ejs
- src/views/auth/signup.ejs
se agregó en la vista de sign up el link del manual de proteccion de datos
https://we.tl/t-MJZLR9LJHp
> link del manual de politica de proteccion de datos

- src/controllers/general_routes.js
- src/public/styles/base/_globals.scss
- src/public/styles/main.css
- src/public/styles/main.scss
- src/public/styles/pages/_products.scss
- src/routes/general_routes.js
- src/views/index.ejs
- src/views/partials/_navbar.ejs
- src/views/products.ejs
Se agregó la vista (solo front) para mostrar los accesorios en venta. 
Es solo front, en las imágenes se puede ver la implementación. 
No aplica.
> Offered accessories

- src/controllers/admin_controller.js
- src/database/SQL/query_db_pi.sql
- src/database/SQL/query_procedures.sql
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/public/styles/main.scss
- src/routes/admin.js
- src/views/admin/existing_accounts.ejs
- src/views/partials/_navbar.ejs
Interfaces para que el administrador pueda modificar el estado de las cuentas. 
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/8a4367c1f0c1468c83adb870ad83a782)
No aplica.
> Admin existing accounts

- src/controllers/general_routes.js
- src/views/products.ejs
Se modifico la ruta /accesories para mostrar los accesorios acorde a la base de datos
Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. 
> Backend US02

- src/libs/protect_middlewares.js
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/routes/admin.js
- src/routes/router_authentication.js
- src/views/auth/create_acc_admin.ejs
- src/views/auth/login.ejs
- src/views/auth/signup.ejs
- src/views/index.ejs
Se agregaron las funciones para protección de rutas de trabajadores, socios, administradores, logueados y no logueados.
No aplica.
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/bc4494e44e5f4f5f8c6d3a5a17b175a8)
No aplica.
> Protección rutas 1

- src/controllers/admin_controller.js
- src/database/SQL/query_procedures.sql
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/routes/admin.js
- src/views/admin/existing_accounts.ejs
Funcionalidad para realizar búsquedas de clientes por parte del administrador. Se puede buscar a partir de:
1. Nombre.
2. Correo.
3. Cédula.
No aplica. 
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/b5d9a6d2674c42ff8182fbe943b055e9)
No aplica.
> Us23 admin search account

- src/controllers/general_routes.js
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/public/styles/main.scss
- src/public/styles/pages/_accessory_details.scss
- src/routes/general_routes.js
- src/views/index.ejs
- src/views/productDetails.ejs
- src/views/products.ejs
Vista y funcionalidad para ver detalles de accesorios.
En el vídeo se muestra. 
[Vídeo corto explicando y mostrando lo que se hizo. ](https://www.loom.com/share/1e175c0ea97c485eb0b25bf5c4bbcb4c)
No aplica.
> Accessory details

- src/views/admin/existing_accounts.ejs
- src/views/admin/inventory_select_existing_accessory.ejs
- src/views/index.ejs
- src/views/productDetails.ejs
- src/views/products.ejs
Se mejoró la accesibilidad de la página por medio de lectores de pantalla mediante el uso del atributo aria-label. 
No aplica. 
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://youtu.be/rZxPcuxBgfY)
No aplica.
> Aria labels

- src/routes/admin.js
- src/views/admin/inventory_select_existing_accessory.ejs
- src/views/index.ejs
- src/views/productDetails.ejs
- src/views/products.ejs
Se agregó la protección a rutas de administrador que no la tenían y se eliminaron '/' innecesarios en la ruta de las imágenes. 
No aplica.
No aplica.
No aplica.
> Protect routes

- src/controllers/controller_auth.js
- src/database/SQL/query_procedures.sql
- src/libs/passport.js
- src/public/scripts/validations/signupBusiness_validaje.js
- src/routes/router_authentication.js
- src/views/auth/signup_business.ejs
Creación de cuentas para empresas y validación del documento no repetido. 
No aplica.
Leer commits.
> Signup business

- src/views/index.ejs
El section de "Nuestros servicios" estaba dentro del condicional de "Featured products", por tanto, si no habían productos destacados, no se veía la sección de "Nuestros servicios".
No aplica. 
No aplica. 
No aplica.
> Fix on home

- src/controllers/cart_controller.js
- src/controllers/employee_controller.js
- src/database/SQL/query_procedures.sql
- src/database/SQL/query_triggers.sql
- src/database/SQL/query_views.sql
- src/index.js
- src/public/scripts/addSub.js
- src/public/scripts/cart_order_search_client.js
- src/public/styles/main.css
- src/public/styles/pages/_carrito.scss
- src/routes/employee.js
- src/routes/router.js
- src/views/partials/_navbar.ejs
- src/views/shop/employee_shopping_cart.ejs
- src/views/shop/shopping_cart.ejs
Se añadió la funcionalidad para que el trabajador registre ordenes de compra en caja. 
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/47cf356dcd694adebce50d8058c9075f)
**Revisar los comentarios del pull request y los .sql.**
> GENERACIÓN DE ORDENES DE COMPRA EN CAJA

- src/libs/passport.js
Solución del bug encontrado en el PR #143 por @diegoaach . 
Anteriormente se serializaba y deserializaba el usuario a partir de su correo, pero como el correo era un dato que el usuario podía cambiar, podían llegar a haber problemas con la sesión. Ahora, se serializa y deserializaba a partir del id del usuario, **EL CUAL NO CAMBIA.**
No aplica. 
No aplica. 
**Funcionamiento:** Inicialmente, se había optado por serializar el usuario a partir de su mail ya que no se tenía manera de, inicialmente, obtener su id, pero se modificó el procedure de creación para que una vez cree el usuario, retorne su id, permitiendo serializar y des-serializar a partir del id (que es fijo).
> Fix passport serialize

- src/controllers/general_routes.js
- src/libs/helpers.js
- src/public/scripts/validations/update_acc_validate.js
- src/routes/general_routes.js
- src/views/partials/_navbar.ejs
- src/views/userUpdate.ejs
Se permite actualizar correo, direccion, telefono y contraseña mediante un formulario
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/e122fffa26344898b23b16e18bf08b27)
> Us11 user info update

- src/public/styles/layouts/_nav.scss
- src/public/styles/main.css
- src/views/partials/_navbar.ejs
Habían problemas con la barra de navegación ya que había mucho texto y no se mostraban todas las opciones, por tanto: 
Se resumieron algunos nombre en opciones de navegación de la barra de navegación para ocupar menos espacio.
También se disminuyeron algunos espaciados dentro de la barra de navegación.
No aplica. 
No aplica. 
No aplica.
> Summarize nav

- src/index.js
La sesión de los usuarios es guardada en la tabla "sessions" de la base de datos. 
No aplica.
No aplica.
> Use express-mysql-session

- src/controllers/admin_controller.js
- src/database/SQL/query_init.sql
- src/database/SQL/query_procedures.sql
- src/views/auth/create_acc_admin.ejs
Se hicieron cambios para:
-Evitar que en la modificación de un accesorio se pueda tomar el nombre de uno ya existente.
-Se anexó el procedure para lo anterior, que comprueba si ya existe un accesorio.
-Se anexó unique index para el campo de nombre, en la tabla accesorios
-Se modificó el for de un label en la vista de creación de cuenta desde admin. con el fin de mejorar rendimiento.
Ninguno.
No aplica. 
Ver commits.
> Hotfix de arreglos solicitados en las pruebas para SilviaPabon

- src/views/admin/existing_accounts_state.ejs
Se hizo un cambio o corrección expuesto por Lighthouse para corregir un Aria repetido.
Ninguno.
Ninguno. 
En el commit queda más claro lo sucedido.
> hotfix aria

- src/controllers/partner_controller.js
- src/routes/partner.js
- src/views/partials/_navbar.ejs
- src/views/partner/existing_accounts_partner.ejs
Creacion de la vista para, como socio, poder ver las cuentas de los clientes que se encuentran activas que aceptaron las politicas de tratamiento de la informacion. Ademas permite filtrarlas por un criterio de busqueda
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo.](https://www.loom.com/share/49fe47cbbeb44870927361f4fb019d27) 
> Us18 partner user search

- src/views/partials/_navbar.ejs
Al dar click sobre el logo, se envía al home de la página.
No aplica.
No aplica.
No aplica.
> Logo redirects to home

- src/controllers/partner_controller.js
- src/routes/partner.js
- src/views/partials/_navbar.ejs
- src/views/partner/partners_inventory.ejs
Se creó la vista completamente funcional del inventario existente para los socios de la empresa, donde les permite tanto ver el inventario como poder buscar con la barra de búsqueda los productos que deseen.
https://www.loom.com/share/31c8a38afb52419d80e9a3d1e37657bd
se completó la historia de usuario 19
> visualizacion de inventario existente para los socios

- src/controllers/cart_controller.js
- src/public/scripts/addSub.js
- src/routes/cart_api.js
- src/views/clients/orders_clients.ejs
- src/views/partials/_navbar.ejs
- src/views/shop/shopping_cart.ejs
Se permite generar una orden de compra a partir de los accesorios seleccionados al decir que se desea comprar, vaciando el carrito de compras y dirigiéndose a la ventana de órdenes.
No aplica.
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo](https://www.loom.com/share/bb04e4cb1fcd4382afe600ea2f10eee5). 
Ver los comentarios de commits.
> Us7client order

- src/database/SQL/query_procedures.sql
Se anexaron procedimientos sobre órdenes de compra según algunos criterios y para muestra de mensajes, para facilitar labores de futuras interfaces.
No aplica.
No aplica. 
Favor de probar los scripts.
> us-43 Update query_procedures.sql

- src/controllers/partner_controller.js
Se muestra el botón de "Volver a todos los accesorios" cuando no se encuentran resultados con el criteio de búsqueda.
No aplica.
No aplica.
> Fix and prettier usage

- src/controllers/cart_controller.js
- src/controllers/user_controllers.js
- src/database/SQL/query_procedures.sql
- src/database/SQL/query_views.sql
- src/index.js
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/routes/cart_api.js
- src/routes/router.js
- src/routes/user.js
- src/views/clients/orders_clients.ejs
- src/views/partials/_navbar.ejs
Funcionalidad para que los clientes vean sus órdenes de compra.
[VÍDEO DE LA FUNCIOINALIDAD ](https://www.loom.com/share/16fde4cea34948868c5c4a3ffe123993)
No aplica.
> Us08 client orders

- package-lock.json
- package.json
- src/controllers/user_controllers.js
- src/database/SQL/query_init.sql
- src/database/SQL/query_procedures.sql
- src/database/SQL/query_views.sql
- src/routes/user.js
- src/views/clients/orders_clients.ejs
Funcionalidad para que el cliente pueda ver su factura de compra en formato PDF.
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/1b2d158e2c004764a34bea9271a29089)
No aplica.
> Us10 client bill

- src/controllers/admin_controller.js
- src/controllers/general_routes.js
- src/controllers/partner_controller.js
- src/public/scripts/validations/contact_us_validate.js
- src/public/scripts/validations/signupBusiness_validaje.js
- src/public/scripts/validations/signup_admin_validate.js
- src/public/scripts/validations/signup_validate.js
- src/views/auth/create_acc_admin.ejs
- src/views/auth/signup.ejs
- src/views/auth/signup_business.ejs
- src/views/contact_us.ejs
- src/views/employees/existing_inventory.ejs
- src/views/partner/existing_accounts_partner.ejs
- src/views/partner/partners_inventory.ejs
Ver los comentarios de los commits y el video.
No aplica.
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/ba28c85a101d48e5bd08562daa1284e7)
No aplica.
> Fix try catch

- src/controllers/employee_controller.js
- src/database/SQL/query_procedures.sql
- src/routes/employee.js
- src/views/employees/employee_show_orders.ejs
- src/views/partials/_navbar.ejs
Interfaz para mostrar al trabajador las ordenes de compra de los clientes.
Mostrar al trabajador las ordenes de compra de los clientes.
https://www.loom.com/share/a2370bc1d0c94590910977e0411d8ed9
Cualquier comentario adicional, por ejemplo, en caso de solicitar no eliminar la rama al hacer merge, explicar qué tiene pensado hacer con la rama.
> Ordenes compra clientes para trabajadores

- docs/Services/MAIL/DOVECOT/conf.d/10-auth.conf
- docs/Services/MAIL/DOVECOT/conf.d/10-mail.conf
- docs/Services/MAIL/DOVECOT/conf.d/10-master.conf
- docs/Services/MAIL/DOVECOT/dovecot.conf
- docs/Services/MAIL/POSTFIX/main.cf
- docs/Services/MAIL/POSTFIX/master.cf
Archivos modificados ocn la configuración necesaria para el funcionamiento de los servicios Postfix y Dovecot configurados en la máquina virtual Ubuntu Server.
No aplica.
No aplica.
No aplica.
> POSTFIX AND DOVECOT FILES

- docs/Services/HTTPS/nginx.conf
Archivo de la configuracion del servidor HTTPS
N/A
N/A
N/A
> HTTPS Conf file

- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/views/admin/existing_accesory_modify.ejs
- src/views/admin/existing_accessory.ejs
- src/views/admin/existing_accounts_state.ejs
- src/views/admin/new_accessory.ejs
- src/views/auth/create_acc_admin.ejs
- src/views/auth/login.ejs
- src/views/auth/signup.ejs
- src/views/auth/signup_business.ejs
- src/views/contact_us.ejs
- src/views/employees/refunds.ejs
- src/views/shop/employee_shopping_cart.ejs
- src/views/userUpdate.ejs
Fix al problema de los inputs que hacía que los formularios se enviaran sin validar los campos al precionar ENTER identificado por @diegoaach .
No aplica.
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/b4ee24123e194c0b84d92537c661e0b8)
No aplica.
> Fix forms ENTER key problem

- src/controllers/general_routes.js
- src/database/SQL/query_procedures.sql
- src/public/styles/components/_components.scss
- src/public/styles/main.css
- src/views/admin/inventory_select_existing_accessory.ejs
- src/views/index.ejs
- src/views/products.ejs
Ver vídeo y capturas.
Vistas de clientes:
Vista de admin:
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/5e83e27aa5df468d94c132485a8ddd7a)
No aplica.
> Styling solf out accessories

- src/controllers/user_controllers.js
- src/public/scripts/recieved.js
- src/routes/user.js
- src/views/clients/orders_clients.ejs
el cliente puede cambiar su estado de compra a recibido, y se le muestra una alerta de confirmación antes de esto
[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. 
](https://www.loom.com/share/303346143ae2422ea56098d41656f680)
> US-09 completada
